frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
    target: production  # Add this line
  container_name: instagram-analytics-frontend
  ports:
    - "80:80"  # Change from 3000:3000 to 80:80
  environment:
    - REACT_APP_API_URL=http://backend:5000
  depends_on:
    - backend
  networks:
    - instagram-analytics-network
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
